# Sample configuration file. See README.config_file for details.

# User interface font settings

ui.control_font=Liberation Sans 20
ui.user_font=Liberation Sans 20
ui.document.font.size=16

# History settings

history.size=30
# History is not saved between sessions, unless you specify
#  a file to save it to.
#history.file=/path/to/.jgemini.history

# Theme settings

# Theme can be 'light', 'dark', or 'custom'
ui.document.theme=light

# If theme is "custom", specify the path to a CSS file
# ui.document.custom.css=/path/to/file.css

# Initial window size

window.w=1200
window.h=900

# Inline image settings

gemtext.inline.images=1
inline.image.width=400

# URL bar settings

urlbar.search.enabled=1
urlbar.search.url=gemini://tlgs.one/search

# Logging level, 0-3 

log.level=0

