# Sample configuration file. See README.config_file for details.

# User interface font settings

ui.control_font=Liberation Sans 20
ui.user_font=Liberation Sans 20
ui.document.font.size=16

# History settings

history.size=30
# Set history.enabled=yes to allow JGemini to save URL history
history.enabled=no
# Set history.file if you want to save history to a custom file
#history.file=/path/to/.jgemini.history

# Theme settings

# Theme can be 'light', 'dark', or 'custom'
ui.document.theme=light

# If theme is "custom", specify the path to a CSS file
# ui.document.custom.css=/path/to/file.css

# Initial window size

window.w=1200
window.h=900

# Inline image settings

gemtext.inline.images=yes
inline.image.width=400

# URL bar settings

urlbar.search.enabled=yes
urlbar.search.url=gemini://tlgs.one/search

# Logging level, 0-3 

log.level=0

