# This is a sample configuration file for JGemini
# Lines beginning '#' are comments
# The sample settings in this file are the same as the
#   defaults, and don't need to be changed unless
#   you want to.

#
# User interface font settings. All sizes are in pixels.
#

# Menu and control fonts
#ui.control_font=Sans 20; Emoji 20
#ui.user_font=Sans 20; Emoji 20

#
# Unicode emoji settings
#
# If emoji.strip.bookmarks is 'yes', remove emojis from bookmarks
# The default is to leave them alone.
#emoji.strip.bookmarks=yes

# Document font base size; heading sizes, etc., are 
#  calculated by scaling this.
#ui.document.font.size=16

#
# URL History settings
#

# Set history.enabled=yes to allow JGemini to save URL history
# The default is not to save history between sessions
#history.enabled=yes

# Number of lines of history to save
#history.size=30

# Set history.file if you want to save history to a custom file
#history.file=/path/to/.jgemini.history

#
# Theme settings
#

# Theme can be 'light', 'dark', or 'custom'
#ui.document.theme=light

# If theme is "custom", specify the path to a CSS file
#ui.document.custom.css=/path/to/file.css

#
# Layout settings
#

# Initial window size
#window.w=1200
#window.h=900

#
# Inline image settings
#

# Set yes or no to enable or disable the display of images
#   automatically withing a Gemtext document. The default
#   is yes
#gemtext.inline.images=yes

# Size of all inline images
#inline.image.width=400

#
# URL bar settings
#

# Set yes or no to enable or disable searching directly
#   from the URL bar. The default is yes.
#urlbar.search.enabled=yes

# URL bar search provider
#urlbar.search.url=gemini://tlgs.one/search

#
# Debugging settings
#

# Logging level, 0-3 
#log.level=0

